#!/sbin/sh

echo "activating aromafm" > /sdcard/aromafm_activator.log

if [ -e /sdcard/aromafm.zip ]
then

echo "found" >> /sdcard/aromafm_activator.log

else

echo "not found" >> /sdcard/aromafm_activator.log
echo "copying default files" >> /sdcard/aromafm_activator.log
cat /res/aromafm/currentversion >> /sdcard/aromafm_activator.log
cp /res/aromafm/aromafm.zip /sdcard/.
cp /res/aromafm/aromafm.zip.cfg /sdcard/.
echo "done" >> /sdcard/aromafm_activator.log

fi

